spring.application.name=RatingsCatalog

server.port=8082

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=refresh

eureka.client.service-url.defaultZone = http://localhost:8761/eureka/

spring.mongodb.uri = mongodb+srv://jacksonsilva_db_user:wJXOt3q60D8Xg0D4@clusterratings.2fdxbyi.mongodb.net/?appName=ClusterRatings